// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// Generated by tool/generate_gasless_rpc_exceptions.py from:
// - mm2src/coins/eth/tron/gasfree/error.rs
// - mm2src/mm2_main/src/rpc/lp_commands/gasless.rs
// - mm2src/mm2_main/src/rpc/streaming_activations/gasless_trace.rs

import 'package:komodo_defi_types/komodo_defi_type_utils.dart';

abstract interface class GaslessRpcErrorType {
  String get wireValue;
}

abstract class GaslessEndpointException<T extends GaslessRpcErrorType>
    implements Exception {
  const GaslessEndpointException({
    required this.type,
    this.errorData,
    this.message,
    this.path,
    this.trace,
  });

  final T type;
  final Object? errorData;
  final String? message;
  final String? path;
  final String? trace;

  String get errorType => type.wireValue;

  JsonMap toJson() => {
    'error_type': errorType,
    'error_data': errorData,
    if (message != null) 'error': message,
    if (path != null) 'error_path': path,
    if (trace != null) 'error_trace': trace,
  };

  @override
  String toString() =>
      '$runtimeType(errorType: $errorType, message: $message, path: $path)';
}

enum GaslessWithdrawErrorType implements GaslessRpcErrorType {
  unavailable('Unavailable'),
  pendingTransfer('PendingTransfer'),
  maxFeeExceeded('MaxFeeExceeded'),
  providerRejected('ProviderRejected'),
  invalidProviderResponse('InvalidProviderResponse'),
  traceNotFound('TraceNotFound'),
  quoteExpired('QuoteExpired'),
  insufficientGasFreeBalance('InsufficientGasFreeBalance'),
  insufficientGasFreeBalanceForActivation(
    'InsufficientGasFreeBalanceForActivation',
  );

  const GaslessWithdrawErrorType(this.wireValue);

  @override
  final String wireValue;

  static GaslessWithdrawErrorType? tryParse(String value) {
    for (final type in values) {
      if (type.wireValue == value) return type;
    }
    return null;
  }
}

enum GaslessAccountStatusErrorType implements GaslessRpcErrorType {
  coinNotFound('CoinNotFound'),
  notEthCoin('NotEthCoin'),
  coinNotSupported('CoinNotSupported'),
  gaslessNotConfigured('GaslessNotConfigured'),
  tronRpcUnavailable('TronRpcUnavailable'),
  providerIdentityMismatch('ProviderIdentityMismatch'),
  gasfreeAddressMismatch('GasfreeAddressMismatch'),
  tokenDecimalMismatch('TokenDecimalMismatch'),
  providerError('ProviderError'),
  internalError('InternalError');

  const GaslessAccountStatusErrorType(this.wireValue);

  @override
  final String wireValue;

  static GaslessAccountStatusErrorType? tryParse(String value) {
    for (final type in values) {
      if (type.wireValue == value) return type;
    }
    return null;
  }
}

enum GaslessTraceStatusErrorType implements GaslessRpcErrorType {
  coinNotFound('CoinNotFound'),
  notEthCoin('NotEthCoin'),
  coinNotSupported('CoinNotSupported'),
  gaslessNotConfigured('GaslessNotConfigured'),
  traceNotFound('TraceNotFound'),
  invalidTraceId('InvalidTraceId'),
  providerError('ProviderError'),
  internalError('InternalError');

  const GaslessTraceStatusErrorType(this.wireValue);

  @override
  final String wireValue;

  static GaslessTraceStatusErrorType? tryParse(String value) {
    for (final type in values) {
      if (type.wireValue == value) return type;
    }
    return null;
  }
}

enum GaslessTraceStreamingRequestErrorType implements GaslessRpcErrorType {
  enableError('EnableError'),
  coinNotFound('CoinNotFound'),
  coinNotSupported('CoinNotSupported'),
  gaslessNotConfigured('GaslessNotConfigured'),
  internal('Internal');

  const GaslessTraceStreamingRequestErrorType(this.wireValue);

  @override
  final String wireValue;

  static GaslessTraceStreamingRequestErrorType? tryParse(String value) {
    for (final type in values) {
      if (type.wireValue == value) return type;
    }
    return null;
  }
}

final class GaslessWithdrawException
    extends GaslessEndpointException<GaslessWithdrawErrorType> {
  const GaslessWithdrawException({
    required super.type,
    super.errorData,
    super.message,
    super.path,
    super.trace,
  });

  static GaslessWithdrawException? tryParse(JsonMap json) {
    final outer = _directGaslessError(json);
    if (outer == null || outer['error_type'] != 'Gasless') {
      return null;
    }
    final error = _asJsonMap(outer['error_data']);
    if (error == null) return null;
    final wireType = error['error_type'];
    if (wireType is! String) return null;
    final type = GaslessWithdrawErrorType.tryParse(wireType);
    if (type == null) return null;
    return GaslessWithdrawException(
      type: type,
      errorData: error['error_data'],
      message: outer['error'] as String,
      path: outer['error_path'] as String?,
      trace: outer['error_trace'] as String?,
    );
  }

  @override
  JsonMap toJson() => {
    'error_type': 'Gasless',
    'error_data': {'error_type': errorType, 'error_data': errorData},
    if (message != null) 'error': message,
    if (path != null) 'error_path': path,
    if (trace != null) 'error_trace': trace,
  };
}

final class GaslessAccountStatusException
    extends GaslessEndpointException<GaslessAccountStatusErrorType> {
  const GaslessAccountStatusException({
    required super.type,
    super.errorData,
    super.message,
    super.path,
    super.trace,
  });

  static GaslessAccountStatusException? tryParse(JsonMap json) {
    final outer = _directGaslessError(json);
    if (outer == null) return null;
    final error = outer;
    final wireType = error['error_type'];
    if (wireType is! String) return null;
    final type = GaslessAccountStatusErrorType.tryParse(wireType);
    if (type == null) return null;
    return GaslessAccountStatusException(
      type: type,
      errorData: error['error_data'],
      message: outer['error'] as String,
      path: outer['error_path'] as String?,
      trace: outer['error_trace'] as String?,
    );
  }
}

final class GaslessTraceStatusException
    extends GaslessEndpointException<GaslessTraceStatusErrorType> {
  const GaslessTraceStatusException({
    required super.type,
    super.errorData,
    super.message,
    super.path,
    super.trace,
  });

  static GaslessTraceStatusException? tryParse(JsonMap json) {
    final outer = _directGaslessError(json);
    if (outer == null) return null;
    final error = outer;
    final wireType = error['error_type'];
    if (wireType is! String) return null;
    final type = GaslessTraceStatusErrorType.tryParse(wireType);
    if (type == null) return null;
    return GaslessTraceStatusException(
      type: type,
      errorData: error['error_data'],
      message: outer['error'] as String,
      path: outer['error_path'] as String?,
      trace: outer['error_trace'] as String?,
    );
  }
}

final class GaslessTraceStreamingRequestException
    extends GaslessEndpointException<GaslessTraceStreamingRequestErrorType> {
  const GaslessTraceStreamingRequestException({
    required super.type,
    super.errorData,
    super.message,
    super.path,
    super.trace,
  });

  static GaslessTraceStreamingRequestException? tryParse(JsonMap json) {
    final outer = _directGaslessError(json);
    if (outer == null) return null;
    final error = outer;
    final wireType = error['error_type'];
    if (wireType is! String) return null;
    final type = GaslessTraceStreamingRequestErrorType.tryParse(wireType);
    if (type == null) return null;
    return GaslessTraceStreamingRequestException(
      type: type,
      errorData: error['error_data'],
      message: outer['error'] as String,
      path: outer['error_path'] as String?,
      trace: outer['error_trace'] as String?,
    );
  }
}

JsonMap? _directGaslessError(JsonMap json) =>
    json['error_type'] is String && json['error'] is String ? json : null;

JsonMap? _asJsonMap(Object? value) =>
    value is Map<String, dynamic> ? value : null;
